#include "aecprocessor.h"

// this is how many frames the audio capture seems to send

#include "common.h"
#include "global.h"


bool PREPROCESSOR = true;

// I tested this to be the best or at least close enough
// this is also recommended by speex documentation
// if you are in a large room, optimal time may be larger.
const int REVERBERATION_TIME_MS = 100;

AECProcessor::AECProcessor(QAudioFormat format):
  format_(format),
  samplesPerFrame_(format.sampleRate()/AUDIO_FRAMES_PER_SECOND),
  preprocessor_(nullptr),
  echo_state_(nullptr),
  echoSize_(0)
{
  init();
}


void AECProcessor::init()
{
  if (preprocessor_ != nullptr || echo_state_ != nullptr)
  {
    cleanup();
  }

  echoMutex_.lock();

  // should be around 1/3 of the room reverberation time
  uint16_t echoFilterLength = format_.sampleRate()*REVERBERATION_TIME_MS/1000;

  printNormal(this, "Initiating echo frame processing", {"Filter length"}, {
                QString::number(echoFilterLength)});

  if(format_.channelCount() > 1)
  {
    echo_state_ = speex_echo_state_init_mc(samplesPerFrame_,
                                           echoFilterLength,
                                           format_.channelCount(),
                                           format_.channelCount());
  }
  else
  {
    echo_state_ = speex_echo_state_init(samplesPerFrame_, echoFilterLength);
  }

  echoSize_ = samplesPerFrame_*format_.bytesPerFrame();
  echoSample_ = createEmptyFrame(echoSize_);

  if (PREPROCESSOR)
  {
    preprocessor_ = speex_preprocess_state_init(samplesPerFrame_,
                                                format_.sampleRate());

    void* activeState = new int(1);
    speex_preprocess_ctl(preprocessor_,
                         SPEEX_PREPROCESS_SET_AGC, activeState);
    speex_preprocess_ctl(preprocessor_,
                         SPEEX_PREPROCESS_SET_DENOISE, activeState);
    //speex_preprocess_ctl(preprocessor_,
    //                     SPEEX_PREPROCESS_SET_DEREVERB, state);

    printNormal(this, "Set global audio preprocessor options");

    speex_preprocess_ctl(preprocessor_,
                         SPEEX_PREPROCESS_SET_ECHO_STATE,
                         echo_state_);
  }

  echoMutex_.unlock();
}


void AECProcessor::cleanup()
{
  echoMutex_.lock();

  if (preprocessor_ != nullptr)
  {
    speex_preprocess_state_destroy(preprocessor_);
    preprocessor_ = nullptr;
  }

  if (echo_state_ != nullptr)
  {
    speex_echo_state_destroy(echo_state_);
    echo_state_ = nullptr;
  }

  echoMutex_.unlock();
}


std::unique_ptr<uchar[]> AECProcessor::processInputFrame(std::unique_ptr<uchar[]> input,
                                                         uint32_t dataSize)
{
  // The audiocapturefilter makes sure the frames are the correct (samplesPerFrame_) size.
  if (dataSize != samplesPerFrame_*format_.bytesPerFrame())
  {
    printProgramError(this, "Wrong size of input frame for AEC");
    return nullptr;
  }

  echoMutex_.lock();

  // do not know if this is allowed, but it saves a copy
  int16_t* pcmOutput = (int16_t*)input.get();
  speex_echo_cancellation(echo_state_,
                          (int16_t*)input.get(),
                          (int16_t*)echoSample_.get(), pcmOutput);

  echoMutex_.unlock();

  // Do preprocess trickery defined in init for input.
  // In my understanding preprocessor is run after echo cancellation for some reason.
  if(preprocessor_ != nullptr)
  {
    speex_preprocess_run(preprocessor_, (int16_t*)input.get());
  }

  return input;
}


void AECProcessor::processEchoFrame(std::shared_ptr<uchar[]> echo,
                                    uint32_t dataSize)
{
  // TODO: This should prepare for different size of frames in case since they
  // are not generated by us
  if (dataSize != samplesPerFrame_*format_.bytesPerFrame())
  {
    printPeerError(this, "Wrong size of echo frame for AEC. AEC will no operate");
    return;
  }

  echoMutex_.lock();
  echoSize_ = dataSize;
  echoSample_ = std::move(echo);
  echoMutex_.unlock();
}


std::shared_ptr<uchar[]> AECProcessor::createEmptyFrame(uint32_t size)
{
  std::shared_ptr<uchar[]> outputSample_
      = std::shared_ptr<uint8_t[]>(new uint8_t[size]);
  memset(outputSample_.get(), 0, size);
  return outputSample_;
}
