#include "speexaec.h"

#include <QSettings>

#include "settingskeys.h"

#include "common.h"
#include "global.h"

// I tested this to be the best or at least close enough
// this is also recommended by speex documentation
// if you are in a large room, optimal time may be larger.
const int REVERBERATION_TIME_MS = 100;


SpeexAEC::SpeexAEC(QAudioFormat format):
  format_(format),
  samplesPerFrame_(format.sampleRate()/AUDIO_FRAMES_PER_SECOND),
  echoMutex_(),
  echo_state_(nullptr),
  preprocessor_(nullptr),
  echoSize_(0),
  echoSample_(nullptr),
  enabled_(false)
{}


void SpeexAEC::updateSettings()
{
  if ( preprocessor_ != nullptr)
  {
    enabled_ = settingEnabled(SettingsKey::audioAEC);

    echoMutex_.lock();

    if (enabled_)
    {
      speex_preprocess_ctl(preprocessor_, SPEEX_PREPROCESS_SET_ECHO_STATE, echo_state_);

      // these are the default values
      int* suppression = new int(-40);
      speex_preprocess_ctl(preprocessor_,
                           SPEEX_PREPROCESS_SET_ECHO_SUPPRESS,
                           suppression);

      *suppression = -15;
      speex_preprocess_ctl(preprocessor_,
                           SPEEX_PREPROCESS_SET_ECHO_SUPPRESS_ACTIVE,
                           suppression);

      delete suppression;
    }
    else
    {
      speex_preprocess_ctl(preprocessor_, SPEEX_PREPROCESS_SET_ECHO_STATE, nullptr);
    }

    echoMutex_.unlock();
  }
}


void SpeexAEC::init()
{
  if (preprocessor_ != nullptr || echo_state_ != nullptr)
  {
    cleanup();
  }

  echoMutex_.lock();


  // should be around 1/3 of the room reverberation time
  uint16_t echoFilterLength = format_.sampleRate()*REVERBERATION_TIME_MS/1000;

  printNormal(this, "Initiating echo frame processing", {"Filter length"}, {
                QString::number(echoFilterLength)});

  if(format_.channelCount() > 1)
  {
    echo_state_ = speex_echo_state_init_mc(samplesPerFrame_,
                                           echoFilterLength,
                                           format_.channelCount(),
                                           format_.channelCount());
  }
  else
  {
    echo_state_ = speex_echo_state_init(samplesPerFrame_, echoFilterLength);
  }

  // set echo sample rate
  int sampleRate = format_.sampleRate();
  speex_echo_ctl(echo_state_, SPEEX_ECHO_SET_SAMPLING_RATE, &sampleRate);

  if (echoSample_ != nullptr)
  {
    delete echoSample_;
    echoSample_ = nullptr;
    echoSize_ = 0;
  }

  echoSize_ = samplesPerFrame_*format_.bytesPerFrame();
  echoSample_ = createEmptyFrame(echoSize_);

  preprocessor_ = speex_preprocess_state_init(samplesPerFrame_,
                                              format_.sampleRate());

  echoMutex_.unlock();

  updateSettings();
}


void SpeexAEC::cleanup()
{
  echoMutex_.lock();

  if (preprocessor_ != nullptr)
  {
    speex_preprocess_state_destroy(preprocessor_);
    preprocessor_ = nullptr;
  }

  if (echo_state_ != nullptr)
  {
    speex_echo_state_destroy(echo_state_);
    echo_state_ = nullptr;
  }

  echoMutex_.unlock();
}


std::unique_ptr<uchar[]> SpeexAEC::processInputFrame(std::unique_ptr<uchar[]> input,
                                                     uint32_t dataSize)
{
  if (enabled_)
  {
    if (dataSize != samplesPerFrame_*format_.bytesPerFrame())
    {
      printProgramError(this, "Wrong size of input frame for AEC");
      return nullptr;
    }

    echoMutex_.lock();

    if (echoSample_ != nullptr)
    {
      std::unique_ptr<uchar[]> pcmOutput = std::unique_ptr<uchar[]>(new uchar[dataSize]);

      if (echo_state_)
      {
        speex_echo_cancellation(echo_state_,
                                (int16_t*)input.get(),
                                (int16_t*)echoSample_, (int16_t*)pcmOutput.get());
      }
      else
      {
        printProgramWarning(this, "Echo state not set");
      }

      if(preprocessor_ != nullptr)
      {
        speex_preprocess_run(preprocessor_, (int16_t*)pcmOutput.get());
      }
      else
      {
        printProgramWarning(this, "Echo preprocessor not set");
      }

      //memcpy(input.get(), pcmOutput, dataSize);
      echoMutex_.unlock();

      return pcmOutput;
    }
    else
    {
      printWarning(this, "No echo reference frame set. Not doing echo cancellation");
    }

    echoMutex_.unlock();
  }

  return input;
}


void SpeexAEC::processEchoFrame(uint8_t *echo,
                                uint32_t dataSize)
{
  // TODO: This should prepare for different size of frames in case since they
  // are not generated by us
  if (dataSize != samplesPerFrame_*format_.bytesPerFrame())
  {
    printError(this, "Wrong size of echo frame for AEC. AEC will not operate");
    return;
  }

  echoMutex_.lock();

  if (echoSample_ == nullptr || echoSize_ != dataSize)
  {
    if (echoSample_ != nullptr)
    {
      delete echoSample_;
      echoSample_ = nullptr;
      echoSize_ = 0;
    }

    echoSize_ = dataSize;
    echoSample_ = createEmptyFrame(echoSize_);
  }
  echoSize_ = dataSize;

  // I don't like this memcpy, but visual studio had some problems with smart pointers.
  memcpy(echoSample_, echo, dataSize);
  echoMutex_.unlock();
}


uint8_t* SpeexAEC::createEmptyFrame(uint32_t size)
{
  uint8_t* emptyFrame  = new uint8_t[size];
  memset(emptyFrame, 0, size);
  return emptyFrame;
}
