#pragma once

#include <cstdint>
#include <memory>
#include <random>
#include <unordered_set>


/* A singleton class helping to generate new SSRCs */

// TODO: Also input ssrcs generated by peers so we don't collide

class SSRCGenerator
{
public:

  ~SSRCGenerator();

    // initializers generator if it does not exist
  static uint32_t generateSSRC();


private:
  SSRCGenerator();

  uint32_t newSSRC();

  static std::unique_ptr<SSRCGenerator> instance_;

  std::mt19937 rng_;
  std::unordered_set<uint32_t> previousSSRCs_;
};
