# dependencies
find_package(Cryptopp QUIET)
find_package(Kvazaar QUIET)
find_package(libyuv QUIET)
find_package(OpenHEVC QUIET)
find_package(Opus QUIET)
find_package(SpeexDSP QUIET)
find_package(uvgRTP QUIET)

# do another check with pkgConfig in case the first one failed
find_package(PkgConfig QUIET)
if(PkgConfig_FOUND)
    if (NOT CRYPTOPP_FOUND)
        pkg_search_module(CRYPTOPP libcrypto++ cryptopp)
    endif()
    if (NOT KVAZAAR_FOUND)
        pkg_search_module(KVAZAAR libkvazaar kvazaar)
    endif()
    if (NOT LIBYUV_FOUND)
        pkg_search_module(LIBYUV yuv libyuv)
    endif()
    if (NOT OPENHEVC_FOUND)
        pkg_search_module(OPENHEVC OpenHEVC LibOpenHevcWrapper OpenHevcWrapper)
    endif()
    if (NOT OPUS_FOUND)
        pkg_search_module(OPUS opus libopus)
    endif()
    if (NOT SPEEXDSP_FOUND)
        pkg_search_module(SPEEXDSP libspeexdsp speexdsp)
    endif()
    if (NOT UVGRTP_FOUND)
        pkg_search_module(UVGRTP uvgrtp uvgRTP)
    endif()
endif()

if (CRYPTOPP_FOUND)
    message(STATUS "Found Crypto++")
else()
    message(STATUS "Did not find Crypto++")
endif()

if (KVAZAAR_FOUND)
    message(STATUS "Found Kvazaar")
else()
    message(STATUS "Did not find Kvazaar")
endif()

if (LIBYUV_FOUND)
    message(STATUS "Found libyuv")
else()
    message(STATUS "Did not find libyuv")
endif()

if (OPENHEVC_FOUND)
    message(STATUS "Found OpenHEVC")
else()
    message(STATUS "Did not find OpenHEVC")
endif()

if (OPUS_FOUND)
    message(STATUS "Found Opus")
else()
    message(STATUS "Did not find Opus")
endif()

if (SPEEXDSP_FOUND)
    message(STATUS "Found SpeexDSP")
else()
    message(STATUS "Did not find SpeexDSP")
endif()

if (UVGRTP_FOUND)
    message(STATUS "Found uvgRTP")
else()
    message(STATUS "Did not find uvgRTP")
endif()


include(dependencies/cryptopp.cmake)
include(dependencies/uvgrtp.cmake)
include(dependencies/openhevc.cmake)
include(dependencies/kvazaar.cmake)
include(dependencies/libyuv.cmake)
include(dependencies/opus.cmake)
include(dependencies/speexdsp.cmake)

# include and link directories for dependencies. 
# These are needed when the compilation happens a second time and the library 
# is found so no compilation happens. Not needed in every case, but a nice backup
include_directories(${CMAKE_BINARY_DIR}/include)
link_directories(${CMAKE_CURRENT_BINARY_DIR}/lib)
